
services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?pgbouncer=true
      DIRECT_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=require
    volumes:
      - .:/app
      - /app/node_modules
    command: ["sh", "-c", "pnpm prisma generate && pnpm dev"]






# run docker-compose up db+web
# services:
#   web:
#     build:
#       context: .
#       target: dev
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: development
#       NEXT_TELEMETRY_DISABLED: "1"
#       DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
#       DIRECT_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
#     volumes:
#       - .:/app
#       - /app/node_modules
#     command: ["sh", "-c", "pnpm prisma generate && pnpm dev"]

#   db:
#     image: postgres:16-alpine
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "${POSTGRES_PORT}:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
